name: PriceChecker

on:
  workflow_dispatch:
jobs:
  price_checker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node_version: "18"
      - name: Install coingeco-api
        run: npm install coingecko-api
      - name: Find assets price
        uses: actions/github-script@v6.3.3
        with:
          retries: 2
          script: |
            const fs = require('fs');
            const CoinGecko = require('coingecko-api');
            const CoinGeckoClient = new CoinGecko();
           
            let assets;
            fs.readFile('assets.json', (err, data) => {
              if (err) throw err;
              assets = JSON.parse(data);
              console.log(assets[asset_name]);
            });
            
            //var getPrice = async(asset_name) => {
            //  let assets;
            //  fs.readFile('assets.json', (err, data) => {
            //    if (err) throw err;
            //    assets = JSON.parse(data);
            //    console.log(assets[asset_name]);
            //  });
            //  let data = await CoinGeckoClient.simple.fetchTokenPrice({
            //    contract_addresses: assets[asset_name],
            //    vs_currencies: 'usd',
            //  });
            //  return data;
            //};

            //const asset_name = "openai-erc"
            //const price = getPrice(asset_name);
            //price.then((value) => {
            //  console.log(value);
              //if (value['code'] == '200') {
              //  const priceValue = value['data'][jsonAsset]['usd'];
              //  console.log(`Price openai-erc: ${priceValue}`);
                // fs.writeFileSync('prices.json', value);
              //} else {
              //  console.error(`Error: value['code']`);
              //};
            //});
