name: PriceChecker

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  price_checker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        asset: ["0x6a6aa13393b7d1100c00a57c76c39e8b6c835041"]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node_version: "18"
      - name: Install coingeco-api
        run: npm install coingecko-api
      - name: Find price of ${{ matrix.asset }}
        uses: actions/github-script@v6.3.3
        with:
          retries: 2
          script: |
            // openai-erc: 0x6a6aa13393b7d1100c00a57c76c39e8b6c835041
            //
            const fs = require('fs');
            const CoinGecko = require('coingecko-api');
            const CoinGeckoClient = new CoinGecko();
            
            var getPrice = async() => {
              var zrx = ${{ matrix.asset }};
              let data = await CoinGeckoClient.simple.fetchTokenPrice({
                contract_addresses: zrx,
                vs_currencies: 'usd',
              });
              return data;
            };

            const price = getPrice();
            price.then((value) => {
              if (value['code'] == '200') {
                const priceValue = value['data'][]['usd'];
                console.log(`Price openai-erc: ${priceValue}`);
              } else {
                console.error(`Error: value['code']`);
              };
            });
