name: PriceChecker

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  price_checker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        asset: ["matic-network", "chainlink"]

    steps:
      - uses: actions/checkout@v3
      - run: |
        curl -X 'GET' 'https://api.coingecko.com/api/v3/coins/chainlink/market_chart?vs_currency=usd&days=90&interval=hourly&precision=2' -H 'accept: application/json' | jq -r > chainlink.json
        curl -X 'GET' \ 'https://api.coingecko.com/api/v3/coins/matic-network/market_chart?vs_currency=usd&days=90&interval=hourly&precision=2' \ -H 'accept: application/json' | jq -r > matic.json
        
        
