name: PriceChecker

on:
  workflow_dispatch:
jobs:
  price_checker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node_version: "18"
      - name: Install coingeco-api
        run: npm install coingecko-api
      - name: Find assets price
        uses: actions/github-script@v6.3.3
        with:
          retries: 2
          script: |
            const fs = require('fs');
            const CoinGecko = require('coingecko-api');
            const CoinGeckoClient = new CoinGecko();
            
            fs.readFile('assets.json', (err, data) => {
              if (err) throw err;
              let assets = JSON.parse(data);
              console.log(assets['openai-erc']);
            });
           
            var getPrice = async(zrx) => {
              let data = await CoinGeckoClient.simple.fetchTokenPrice({
                contract_addresses: zrx,
                vs_currencies: 'usd',
              });
              return data;
            };

            var jsonAsset = assets["openai-erc"]
            const price = getPrice(jsonAsset);
            price.then((value) => {
              console.log(value);
              if (value['code'] == '200') {
                const priceValue = value['data'][jsonAsset]['usd'];
                console.log(`Price openai-erc: ${priceValue}`);
                // fs.writeFileSync('prices.json', value);
              } else {
                console.error(`Error: value['code']`);
              };
            });
