name: PriceChecker

on:
  push:
  workflow_dispatch:
jobs:
  price_checker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node_version: "18"
      - name: Install coingeco-api
        run: npm install coingecko-api
      - name: Find assets price
        uses: actions/github-script@v6.3.3
        with:
          retries: 2
          script: |
            const fs = require('fs');
            const CoinGecko = require('coingecko-api');
            const CoinGeckoClient = new CoinGecko();

            var assets = [
                {'name': 'openai-erc',
                 'address': '0x6a6aa13393b7d1100c00a57c76c39e8b6c835041'},
                {'name': 'oraichain-token',
                 'address': '0x4c11249814f11b9346808179cf06e71ac328c1b5'},
              ];

            var getPrice = async(asset_name, asset_address) => {
              let data = await CoinGeckoClient.simple.fetchTokenPrice({
                contract_addresses: asset_address,
                vs_currencies: "usd",
              });
              return data;
            };

            assets.forEach(function(asset) {
              var assetName = asset.name;
              var assetAddress = asset.address;

              const price = getPrice(assetName, assetAddress);
              price.then((value) => {
                if (value['code'] == '200') {
                  const priceValue = value['data'][assetAddress]['usd'];
                  console.log(`Price ${assetName}: ${priceValue}`);
                //   fs.appendFile('prices.json', value);
                } else {
                  console.error(`Error: value['code']`);
                };
              });
            });
#       - name: Notify
#         run: python notifyme.py

