name: PriceChecker

on:
  push:
  workflow_dispatch:
jobs:
  price_checker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node_version: "18"
      - name: Install coingeco-api
        run: npm install coingecko-api
      - name: Find assets price
        uses: actions/github-script@v6.3.3
        with:
          retries: 2
          script: |
            const fs = require('fs');
            const CoinGecko = require('coingecko-api');
            const CoinGeckoClient = new CoinGecko();
           
            var assets = {};
            var asset_name = "openai-erc";
            
            var getPrice = async(asset_name) => {
              console.log(`Asset name: ${asset_name}`);
              var asset_address = "";
              fs.readFile('assets.json', (err, data) => {
                if (err) throw err;
                assets = JSON.parse(data);
                asset_address = assets[asset_name];
                asset_address = JSON.stringify(asset_address);
                console.log(`Asset address: ${asset_address}`);
                console.log(typeof asset_address);
              });
              let data = await CoinGeckoClient.simple.fetchTokenPrice({
                contract_addresses: asset_address,
                vs_currencies: "usd",
              });
              return data;
            };
            
            const price = getPrice(asset_name);
            price.then((value) => {
              console.log(value);
              //if (value['code'] == '200') {
              //  const priceValue = value['data'][jsonAsset]['usd'];
              //  console.log(`Price openai-erc: ${priceValue}`);
                // fs.writeFileSync('prices.json', value);
              //} else {
              //  console.error(`Error: value['code']`);
              //};
            });
